[tool.poetry]
name = "insatgram-comment-bot"
version = "0.1.0"
description = ""
authors = ["Khalid <hex0119@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"
requests = "^2.23"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
